---
name: "📦 Dependency Review"

on:
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  dependency-review:
    name: "🏭 Scanning"
    runs-on: ubuntu-latest
    steps:
      - name: "⤵️ Check out code from GitHub"
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - name: "🏗 Dependency Review"
        uses: actions/dependency-review-action@c090f4e553673e6e505ea70d6a95362ee12adb94
        with:
          # Possible values: "critical", "high", "moderate", "low"
          fail-on-severity: high
          # Possible values: Any `spdx_id` value(s) from https://docs.github.com/en/rest/licenses
          allow-licenses: GPL-3.0, BSD-3-Clause, MIT
          # Possible values: Any `spdx_id` value(s) from https://docs.github.com/en/rest/licenses
          # deny-licenses: LGPL-2.0, BSD-2-Clause
